#!/bin/bash
# update-frontend-config.sh
# Extracts SAM stack outputs and writes them to frontend/.env.local

set -e

STACK_NAME="${1:-TenderVault}"
REGION="${2:-us-east-1}"

echo "Fetching stack outputs for: $STACK_NAME in $REGION..."

# Get stack outputs
API_ENDPOINT=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" \
  --output text)

USER_POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
  --output text)

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
  --output text)

CLOUDFRONT_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontURL'].OutputValue" \
  --output text)

FRONTEND_BUCKET=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" \
  --output text)

CF_DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
  --output text)

# Write to frontend/.env.local
ENV_FILE="$(dirname "$0")/../../frontend/.env.local"
cat > "$ENV_FILE" << EOF
# Auto-generated by update-frontend-config.sh
# Do not commit this file

VITE_API_URL=${API_ENDPOINT}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
VITE_AWS_REGION=${REGION}
VITE_CLOUDFRONT_URL=${CLOUDFRONT_URL}
VITE_FRONTEND_BUCKET=${FRONTEND_BUCKET}
VITE_CF_DISTRIBUTION_ID=${CF_DIST_ID}
EOF

echo "Frontend config written to: $ENV_FILE"
echo ""
echo "Values:"
echo "  API_URL:           $API_ENDPOINT"
echo "  USER_POOL_ID:      $USER_POOL_ID"
echo "  CLIENT_ID:         $USER_POOL_CLIENT_ID"
echo "  CLOUDFRONT_URL:    $CLOUDFRONT_URL"
echo "  FRONTEND_BUCKET:   $FRONTEND_BUCKET"
echo "  CF_DIST_ID:        $CF_DIST_ID"
